apiVersion: v1
kind: Service
metadata:
  labels:
    app: gameboard
  name: gameboard
  namespace: gameboard
spec:
  type: LoadBalancer
  selector:
    app: gameboard
  ports:
    - port: 80
      targetPort: 80
